package:
  name: yapf
  version: "0.1.7"

source:
  fn: yapf-0.1.7.tar.gz
  url: https://pypi.python.org/packages/source/y/yapf/yapf-0.1.7.tar.gz
  md5: 3392c52666e35a501465df753a72cdce
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - yapf = yapf:main
    #
    # Would create an entry point called yapf that calls yapf.main()

    - yapf = yapf:run_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - yapf
    - yapf.yapflib
    - yapftests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - yapf --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'A formatter for Python code.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
