package:
  name: uncertainties
  version: "2.4.6.1"

source:
  fn: uncertainties-2.4.6.1.tar.gz
  url: https://pypi.python.org/packages/source/u/uncertainties/uncertainties-2.4.6.1.tar.gz
  md5: a30c01fda82b07ceb758e47e4768843f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - uncertainties = uncertainties:main
    #
    # Would create an entry point called uncertainties that calls uncertainties.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - uncertainties
    - uncertainties.lib1to2
    - uncertainties.lib1to2.fixes
    - uncertainties.unumpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonhosted.org/uncertainties/
  license: BSD License
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
