package:
  name: triangle_plot
  version: "0.0.6"

source:
  fn: triangle_plot-0.0.6.tar.gz
  url: https://pypi.python.org/packages/source/t/triangle_plot/triangle_plot-0.0.6.tar.gz
  md5: 970a35a9bde6002d673e3188fe39f0ed
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - triangle_plot = triangle_plot:main
    #
    # Would create an entry point called triangle_plot that calls triangle_plot.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib

test:
  # Python imports
  imports:
    - triangle
    - matplotlib
    - numpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dfm/triangle.py
  license: BSD License
  summary: 'Make some beautiful corner plots of samples.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
