package:
  name: ds9
  version: !!str 1.7

source:
  fn: pyds9-1.7.tar.gz
  url: http://ds9.si.edu/download/pyds9/pyds9-1.7.tar.gz
  md5: 7de4aec09005ed57f4ee1f6af5d4a3f5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - emcee = emcee:main
    #
    # Would create an entry point called emcee that calls emcee.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - ds9

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ds9.si.edu
  license: GPL License
  summary: 'Python interface to the ds9 image viewer'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
